// Default language code is 'pt'
const languageCode = 'pt';

const pt = {
  _fileSuffix: '_pt',
  account: 'Conta',
  actions: 'Acções',
  address: 'Morada',
  adBlueLevel: 'Nível AdBlue',
  addDriver: 'Adicionar Motorista',
  addDriverOk: 'Motorista adicionado com sucesso',
  addDriverNok: 'Erro na adição de Motorista',
  addGeofence: 'Adicionar Cerca Geográfica',
  addGeofenceOk: 'Cerca Geográfica criada com sucesso',
  addGeofenceNok: 'Erro ao criar Cerca Geográfica',
  addGeofenceChooseName: 'Dê um nome à Cerca Geográfica',
  addGeofenceChooseType: 'Escolha o tipo de Cerca Geográfica',
  addGroup: 'Adicionar Grupo',
  addGroupOk: 'Grupo adicionado com sucesso',
  addGroupNok: 'Erro na adição de Grupo',
  addNotification: 'Adicionar Notificação',
  addNotificationOk: 'Notificação adicionada com sucesso',
  addNotificationNok: 'Erro na adição de Notificação',
  addUser: 'Adicionar Utilizador',
  alarm: 'Alarme',
  alarms: 'Alarmes',
  allEvents: 'Todos os eventos',
  allDevices: 'Todos os dispositivos',
  always: 'Sempre',
  areYouSure: 'Tem a certeza?',
  averageSpeed: 'Velocidade Média',
  ambientAirTemperature: 'Temperatura Ar Ambiente',
  analog: 'Analógico',
  birthdayDate: 'Data de Nascimento',
  biweeklyDrivingTime: 'Tempo de trabalho quinzenal',
  biweekly: 'Bissemanal',
  brand: 'Marca',
  card: 'Cartão',
  cardPresent: 'Cartão inserido',
  cardNotPresent: 'Cartão não inserido',
  cardNumber: 'Nº Cartão',
  cancel: 'Cancelar',
  canInformation: 'Informação CAN',
  category: 'Categoria',
  cleanRoutes: 'Limpar Trajetos',
  close: 'Fechar',
  channels: 'Canais',
  chooseEvents: 'Escolha os eventos',
  chooseYourLanguage: 'Escolha o seu idioma',
  chooseYourVehicles: 'Escolha os seus veículos',
  coordinates: 'Coordenadas',
  color: 'Cor',
  constinousDriving: 'Tempo de trabalho continuo',
  date: 'Data',
  diary: 'Diário',
  dashboard: 'Dashboard',
  deleteDriver: 'Apagar Motorista',
  deleteDriverOk: 'Motorista apagado com sucesso',
  deleteDriverNok: 'Erro na eliminação de Motorista',
  deleteGeofence: 'Apagar Cerca',
  deleteGeofenceOk: 'Cerca Geográfica apagada com sucesso',
  deleteGeofenceNok: 'Error na eliminação de Cerca Geográfica',
  deleteGroup: 'Apagar Grupo',
  deleteGroupOk: 'Grupo apagado com sucesso',
  deleteGroupNok: 'Erro na eliminação de Grupo',
  deleteNotification: 'Apagar Notiticação',
  deleteNotificationOk: 'Notificação apagado com sucesso',
  deleteNotificationNok: 'Erro na eliminação de Notificação',
  detailsDriver: 'Detalhes do Motorista',
  detailsVehicle: 'Detalhes do Veículo',
  deviceMoving: 'Dispositivo em movimento',
  deviceName: 'Nome do Dispositivo',
  deviceOffline: 'Dispositivo Offline',
  deviceOnline: 'Dispositivo Online',
  deviceStopped: 'Dispositivo Parado',
  deviceUnknown: 'Dispositivo Desconhecido',
  diesel: 'Gasóleo',
  digital: 'Digital',
  dischargeLocation: 'Local de Descarga',
  distance: 'Distância',
  drive: 'Em condução',
  driveLicenceDateValid: 'Data validade carta condução',
  driveLicenceNumber: 'Nº Carta Condução',
  driver: 'Motorista',
  driverAvailable: 'Motorista Disponível',
  driverChanged: 'Troca de Motorista',
  drivers: 'Motoristas',
  driverState: 'Estado Condutor',
  drivingTime: 'Tempo Condução',
  duration: 'Duração',
  ecoDrive: 'EcoDrive',
  editDriver: 'Editar Motorista',
  editDriverOk: 'Motorista editado com sucesso',
  editDriverNok: 'Erro na edição de motorista',
  editGeofence: 'Edite a Cerca Geográfica',
  editGeofenceOk: 'Cerca Geográfica editada com sucesso',
  editGeofenceNok: 'Erro na edição da Cerca Geográfica',
  editGroup: 'Editar Grupo',
  editGroupOk: 'Grupo editado com sucesso',
  editGroupNok: 'Erro na edição do grupo',
  editVehicle: 'Editar Veículo',
  editVehicleOk: 'Veículo editado com sucesso',
  editVehicleNok: 'Erro na edição de veículo',
  editNotification: 'Editar Notificação',
  editNotificationOk: 'Notificação editada com sucesso',
  editNotificationNok: 'Erro na edição de notficação',
  email: 'E-mail',
  end: 'Fim',
  endAddress: 'Morada de Fim',
  engineCoolantTemperature: 'Temperatura refrigerante motor',
  english: 'Inglês',
  endTime: 'Hora de Fim',
  error: 'Erro!',
  events: 'Eventos',
  extendedDays: 'Dias estendidos',
  fleet: 'Frota',
  follow: 'Seguir',
  from: 'De',
  fuel: 'Combustível',
  fuelLevel: 'Nivel de Combustível',
  gasoline: 'Gasolina',
  geofence: 'Cerca Geográfica',
  geofences: 'Cercas Geográficas',
  geofenceEnter: 'Entrada Cerca Geográfica',
  geofenceExit: 'Saida Cerca Geográfica',
  geofenceTypePolygon: 'Polígono',
  geofenceTypePolygonDescription: 'Seleccione os pontos no mapa onde deseja delimitar uma cerca geográfica',
  geofenceTypeCircle: 'Círculo',
  geofenceTypeCircleDescription: 'Seleccione o ponto no mapa onde deseja centrar a cerca geográfica',
  generateReport: 'Gerar Relatório',
  group: 'Grupo',
  groups: 'Grupos',
  harshAcceleration: 'Aceleração Brusca',
  harshBraking: 'Travagem Brusca',
  harshCornering: 'Viragem Brusca',
  help: 'Ajuda',
  hours: 'Horas',
  hybridMap: 'Google Maps Hydrid',
  hybridTrafficMap: 'Google Maps Hydrid - Traffic',
  identifier: 'Identificador',
  idling: 'Ralenti',
  ignition: 'Ignição',
  ignitionOn: 'Ignição Ligada',
  ignitionOff: 'Ignição Desligada',
  insurance: 'Seguro',
  insuranceCompany: 'Nome da companhia de seguros',
  insuranceDateValid: 'Data validade apólice',
  insurancePolicyNumber: 'Nº apólice',
  internalbattery: 'Bateria Interna',
  language: 'Língua',
  lastUpdate: 'Última Atualização',
  latitude: 'latitude',
  loadingDriversData: 'A obter dados dos motoristas',
  loadingNotificationsData: 'A obter dados das notificações',
  loadingMap: 'A carregar mapa...',
  loadingPlace: 'Local de carga',
  login: 'Login',
  loginFail: 'Nome de utilizador e/ou senha inválidos',
  loginOk: 'Login efetuado com sucesso',
  logout: 'Sair',
  longitude: 'longitude',
  map: 'Mapa',
  mapCannotBeLoadedNow: 'Pedimos desculpa, mas o mapa não pode ser carregado.',
  maintenance: 'Manutenção',
  maxSpeed: 'Velocidade Máxima',
  maxSpeedDetected: 'Velocidade Máxima Permitida',
  mobile: 'Telemóvel',
  mobilePersonal: 'Telemóvel Pessoal',
  mobileWork: 'Telemóvel Trabalho',
  model: 'Modelo',
  moving: 'Movimento',
  name: 'Nome',
  next: 'Avançar',
  nif: 'NIF',
  no: 'Não',
  numberPlate: 'Matricula',
  notAccounted: 'Não Contabilizado',
  notApplicable: 'Não Aplicável',
  notAvailable: '(não disponível)',
  notificationType: 'Tipo de Notificação',
  notification: 'Notificação',
  notifications: 'Notificações',
  odometer: 'Odómetro',
  off: 'Desligada',
  ok: 'Ok',
  on: 'Ligada',
  openStreetMap: 'OpenStreetMap',
  options: 'Opções',
  otherworks: 'Outros trabalhos',
  overallScore: 'Pontuação Geral',
  password: 'Senha',
  passwordChangedWithSuccess: 'Senha guardada com sucesso',
  passwordConfirm: 'Confirmar Senha',
  passwordsDoNotMatch: 'Senhas não são iguais',
  period: 'Periodo',
  personalData: 'Dados Pessoais',
  phone: 'Telefone',
  pleaseWait: 'Por favor, aguarde',
  product: 'Produto',
  profissonalData: 'Dados Profissionais',
  portuguese: 'Português',
  registrationDate: 'Data de Matrícula',
  reports: 'Relatórios',
  rest: 'Em Descanso',
  restTime: 'Tempo de descanso',
  roadmapMap: 'Google Maps Roads',
  roadmapTrafficMap: 'Google Maps Roads - Traffic',
  route: 'Trajeto',
  routes: 'Trajetos',
  rpm: 'Rotações do Motor',
  satelliteMap: 'Google Maps Satellite',
  save: 'Guardar',
  search: 'Procurar...',
  searchLocations: 'Procurar Locais',
  settings: 'Configurações',
  showDrivers: 'Mostrar Motoristas',
  showFleet: 'Mostrar Frota',
  showMarkers: 'Mostrar Marcadores',
  showStops: 'Mostrar Paragens',
  showTripsToday: 'Mostrar viagens de hoje',
  speed: 'Velocidade',
  speedLimit: 'Limite de Velocidade',
  speedlimitexceeded: 'Limite de velocidade excedido',
  stops: 'Paragens',
  stopped: 'Parado',
  start: 'Início',
  startAddress: 'Morada de Início',
  startTime: 'Hora de Início',
  status: 'Estado',
  statusNow: 'Estado Atual',
  submit: 'Submeter',
  success: 'Sucesso',
  summary: 'Resumo',
  tachograph: 'Tacógrafo',
  tachographCalibration: 'Aferição Tacógrafo',
  tachographCard: 'Nº Cartão Tacógrafo',
  tachographCardDateValid: 'Data validade cartão tacógrafo',
  tachographType: 'Tipo tacógrafo',
  terrainMap: 'Google Maps Terrain',
  task: 'Tarefa',
  tasks: 'Tarefas',
  temperature: 'Temperatura',
  to: 'Para',
  today: 'Hoje',
  totalFuelUsed: 'Total Combustível Usado',
  trips: 'Viagens',
  type: 'Tipo',
  typeOfNotification: 'Tipo de Notificação',
  undefined: 'Indefinido',
  undo: 'Desfazer',
  uniqueId: 'Nº Cartão Tacógrafo', // driver
  unknown: 'Desconhecido',
  until: 'Até',
  username: 'Utilizador',
  validatingLogin: 'Estamos a validar o login',
  vehicle: 'Veículo',
  vehicles: 'Veículos',
  voltmeter: 'Voltímetro',
  work: 'Trabalho',
  dailyDrivingTime: 'Tempo de condução diário',
  withoutSignal: 'Sem Sinal',
  weeklyDrivingTime: 'Tempo de condução semanal',
  viaverdeIdentifierNumber: 'Nº Identificador ViaVerde',
  vin: 'VIN',
  web: 'Web',
  weekly: 'Semanal',
  working: 'Em Trabalho',
  year: 'Ano',
  yes: 'Sim',
};

const en = {
  _fileSuffix: '_en',
  account: 'Account',
  actions: 'Actions',
  address: 'Address',
  adBlueLevel: 'AdBlue Level',
  addDriver: 'Add Diver',
  addDriverOk: 'Driver added with success',
  addDriverNok: 'Error adding driver',
  addGroup: 'Add Group',
  addGroupOk: 'Group added with success',
  addGroupNok: 'Error adding group',
  addGeofence: 'Add Geofence',
  addGeofenceOk: 'Geofence was created successfully',
  addGeofenceNok: 'Error creating Geofence',
  addGeofenceChooseName: 'Name this geofence',
  addGeofenceChooseType: 'Choose the geofence type',
  addNotification: 'Add Notification',
  addNotificationOk: 'Notification was added successfully',
  addNotificationNok: 'Error adding notification',
  addUser: 'Add User',
  alarm: 'Alarm',
  alarms: 'Alarms',
  allEvents: 'All Events',
  allDevices: 'All Devices',
  always: 'Always',
  areYouSure: 'Are you sure?',
  averageSpeed: 'Average Speed',
  ambientAirTemperature: 'Ambient Air Temperature',
  analog: 'Analog',
  birthdayDate: 'Birthday Date',
  biweeklyDrivingTime: 'Biweekly Work',
  biweekly: 'Biweekly',
  brand: 'Brand',
  card: 'Card',
  cardPresent: 'Card present',
  cardNotPresent: 'Card not present',
  cardNumber: 'Card Number',
  cancel: 'Cancel',
  canInformation: 'CAN Information',
  category: 'Category',
  cleanRoutes: 'Clear Routes',
  close: 'Close',
  channels: 'Channels',
  chooseEvents: 'Choose Events',
  chooseYourLanguage: 'Choose your language',
  chooseYourVehicles: 'Choose your vehicles',
  color: 'Color',
  coordinates: 'Coordinates',
  constinousDriving: 'Constinous Driving',
  date: 'Date',
  diary: 'Diary',
  dashboard: 'Dashboard',
  deleteDriver: 'Delete Driver',
  deleteDriverOk: 'Driver deleted with success',
  deleteDriverNok: 'Error deleting driver',
  deleteGeofence: 'Delete Geofence',
  deleteGeofenceOk: 'Geofence deleted successfully',
  deleteGeofenceNok: 'Error deleting Geofence',
  deleteGroup: 'Delete Driver',
  deleteGroupOk: 'Group deleted with success',
  deleteGroupNok: 'Error deleting group',
  deleteNotification: 'Delete Notification',
  deleteNotificationOk: 'Notification deleted with success',
  deleteNotificationNok: 'Error deleting notification',
  detailsDriver: 'Details Driver',
  detailsVehicle: 'Details Vehicle',
  deviceMoving: 'Device Moving',
  deviceName: 'Device Name',
  deviceOffline: 'Device Offline',
  deviceOnline: 'Device Online',
  deviceUnknown: 'Device Unknown',
  digital: 'Digital',
  diesel: 'Diesel',
  deviceStopped: 'Device Stopped',
  dischargeLocation: 'Discharge Location',
  distance: 'Distance',
  drive: 'Drive',
  driveLicenceDateValid: 'Drive Licence DateValid',
  driveLicenceNumber: 'Drive Licence Number',
  driver: 'Driver',
  driverAvailable: 'Driver Available',
  driverChanged: 'Driver Change',
  drivers: 'Drivers',
  driverState: ' Driver State',
  drivingTime: 'Driving Time',
  duration: 'Duration',
  ecoDrive: 'EcoDrive',
  editDriver: 'Edit Driver',
  editDriverOk: 'Driver edited with success',
  editDriverNok: 'Error editing driver',
  editGeofence: 'Update the Geofence data',
  editGeofenceOk: 'Geofence edited successfully',
  editGeofenceNok: 'Error editing Geofence',
  editGroup: 'Edit Group',
  editGroupOk: 'Group edited with success',
  editGroupNok: 'Error editing group',
  editVehicle: 'Edit Vehicle',
  editVehicleOk: 'Vehicle edited with success',
  editVehicleNok: 'Error editing vehicle',
  editNotification: 'Edit Notification',
  editNotificationOk: 'Notification edited with success',
  editNotificationNok: 'Error editing notification',
  email: 'E-mail',
  end: 'End',
  endAddress: 'End Address',
  engineCoolantTemperature: 'Engine Coolant Temperature',
  english: 'English',
  endTime: 'End Time',
  error: 'Error!',
  events: 'Events',
  extendedDays: 'Extended Days',
  fleet: 'Fleet',
  follow: 'Follow',
  from: 'From',
  fuel: 'Fuel',
  fuelLevel: 'Fuel Level',
  gasoline: 'Gasoline',
  geofence: 'Geofence',
  geofences: 'Geofences',
  geofenceEnter: 'Geofence Enter',
  geofenceExit: 'Geofence Exit',
  geofenceTypePolygon: 'Polygon',
  geofenceTypePolygonDescription: 'Select the locations on the map where you wish to form a geofence',
  geofenceTypeCircle: 'Circle',
  geofenceTypeCircleDescription: 'Select the location where you want to center the geofence',
  generateReport: 'Generate Report',
  group: 'Group',
  groups: 'Groups',
  harshAcceleration: 'Harsh Acceleration',
  harshBraking: 'Harsh Braking',
  harshCornering: 'Harsh Cornering',
  help: 'Help',
  hours: 'Hours',
  hybridMap: 'Google Maps Hybrid',
  hybridTrafficMap: 'Google Maps Hybrid - Traffic',
  identifier: 'Identifier',
  idling: 'Idling',
  ignition: 'Ignition',
  ignitionOn: 'Ignition On',
  ignitionOff: 'Ignition Off',
  insurance: 'Insurance',
  insuranceCompany: 'Insurance Company',
  insuranceDateValid: 'Insurance Date Valid',
  insurancePolicyNumber: 'Insurance Policy Number',
  internalbattery: 'Internal Battery',
  language: 'Language',
  lastUpdate: 'Last update',
  latitude: 'latitude',
  loadingDriversData: 'Loading drivers data',
  loadingNotificationsData: 'Loading Notifications Data',
  loadingMap: 'Loading Map...',
  loadingPlace: 'Loading Place',
  login: 'Login',
  loginFail: 'Username and/or password is invalid',
  loginOk: 'Login Successful',
  logout: 'Logout',
  longitude: 'longitude',
  map: 'Map',
  mapCannotBeLoadedNow: 'Map cannot be loaded right now, sorry.',
  maintenance: 'Maintenance',
  maxSpeed: 'Max Speed',
  maxSpeedDetected: 'Max Speed Detected',
  mobile: 'Mobile',
  mobilePersonal: 'Mobile Personal',
  mobileWork: 'Mobile Work',
  model: 'Model',
  moving: 'Moving',
  name: 'Name',
  next: 'Next',
  nif: 'NIF',
  no: 'No',
  numberPlate: 'Number plate',
  notAccounted: 'Not Accounted',
  notAvailable: '(not available)',
  notApplicable: 'Not Applicable',
  notificationType: 'Notification Type',
  notification: 'Notification',
  notifications: 'Notifications',
  odometer: 'Odometer',
  off: 'Off',
  ok: 'Ok',
  on: 'On',
  openStreetMap: 'OpenStreetMap',
  options: 'Options',
  otherworks: 'Other Works',
  overallScore: 'Overall Score',
  password: 'Password',
  passwordChangedWithSuccess: 'Password saved with success',
  passwordConfirm: 'Confirm Password',
  passwordsDoNotMatch: 'Passwords don\'t match',
  period: 'Period',
  personalData: 'Personal Data',
  phone: 'Phone',
  pleaseWait: 'Please, wait',
  product: 'Product',
  profissonalData: 'Profissonal Data',
  portuguese: 'Portuguese',
  registrationDate: 'Registration Date',
  reports: 'Reports',
  rest: 'Rest',
  restTime: 'Rest Time',
  roadmapMap: 'Google Maps Roads',
  roadmapTrafficMap: 'Google Maps Roads - Traffic',
  route: 'Route',
  routes: 'Routes',
  rpm: 'RPM',
  satelliteMap: 'Google Maps Satellite',
  save: 'Save',
  search: 'Search...',
  searchLocations: 'Search Locations',
  settings: 'Settings',
  showDrivers: 'Show Drivers',
  showFleet: 'Show Fleet',
  showMarkers: 'Show Markers',
  showStops: 'Show Stops',
  showTripsToday: 'Show trips today',
  speed: 'Speed',
  speedLimit: 'Speed Limit',
  speedlimitexceeded: 'Speed limit exceeded',
  stops: 'Stops',
  stopped: 'stopped',
  start: 'Start',
  startAddress: 'Start Address',
  startTime: 'StartTime',
  status: 'Status',
  statusNow: 'Status Now',
  submit: 'Submit',
  success: 'Success',
  summary: 'Summary',
  tachograph: 'Tachograph',
  tachographCalibration: 'Tachograph Calibration',
  tachographCard: 'Tachograph Card',
  tachographCardDateValid: 'Tachograph Card Date Valid',
  tachographType: 'Tachograph Type',
  terrainMap: 'Google Maps Terrain',
  task: 'Task',
  tasks: 'Tasks',
  temperature: 'Temperature',
  to: 'To',
  today: 'Today',
  totalFuelUsed: 'Total Fuel Used',
  trips: 'Trips',
  type: 'Type',
  typeOfNotification: 'Type of Notification',
  undefined: 'Undefined',
  undo: 'Undo',
  uniqueId: 'Tachograph Card Number', // driver
  unknown: 'Unknown',
  until: 'Until',
  username: 'Username',
  validatingLogin: 'We are validating the login',
  vehicle: 'Vehicle',
  vehicles: 'Vehicles',
  voltmeter: 'Voltmeter',
  work: 'Work',
  dailyDrivingTime: 'Daily Driving Time',
  withoutSignal: 'Without Signal',
  weeklyDrivingTime: 'Weekly Driving Time',
  viaverdeIdentifierNumber: 'ViaVerde Identifier Number',
  vin: 'VIN',
  web: 'Web',
  weekly: 'Weekly',
  working: 'Working',
  year: 'Year',
  yes: 'Yes',
};

exports.get = (code) => {
  if (languageCode === 'pt' && pt[code]) {
    return pt[code];
  }
  if (languageCode === 'en' && en[code]) {
    return en[code];
  }
  return `[MISSING: '${code}' (${languageCode})]`;
};
