export interface VehiclesDTO {
  attributes: {
    brand: string,
    insuranceDateValid: string,
    insurancePolicyNumber: string,
    registrationDate: string,
    speedLimit: number,
    tachographCalibration: string,
    vin: string,
  },
  category: string,
  contact: string,
  disabled: boolean,
  geofenceIds: boolean,
  groupId: number,
  id: number,
  lastUpdate: string,
  model: string,
  name: string,
  phone: string,
  positionId: number,
  status: string,
  uniqueId: string,
}
