export interface VehicleDetailsTripsDTO {
  averageSpeed: number,
  deviceId: number ,
  deviceName: string,
  distance: number,
  driverName: null,
  driverUniqueId: number,
  duration: number ,
  endAddress: string,
  endLat: number,
  endLon: number ,
  endOdometer: number ,
  endPositionId: number ,
  endTime: string,
  maxSpeed: number ,
  spentFuel: number ,
  startAddress: string,
  startLat: number ,
  startLon: number ,
  startOdometer: number ,
  startPositionId: number ,
  startTime: string,
}